config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :themes
  resources :posts, only: [:index, :show]
  resources :subscriptions
  resources :profiles

  resources :users do
    resources :comments
    resources :profiles, only: [:new, :create, :show, :edit, :update]
  end

  resources :themes do
    resources :tasks
  end

  resources :posts do
    resources :tasks
  end


  resources :tasks do
    resources :answers

    member do
      post 'like', to: 'likes#create'
      delete 'unlike', to: 'likes#destroy'
    end
  end

  resources :answers do
    resources :comments

    resources :likes, only: [:index, :show, :create, :update, :destroy]

    member do
      post 'like', to: 'likes#create'
      delete 'unlike', to: 'likes#destroy'
    end

  end

  # LOGIN AND AUTHORISE


  # API V1 version, fixing process
  namespace :api, format: "json" do
    namespace :v1 do
      resources :answers, only: [ :index, :show ]
      resources :themes, only: [ :index, :show ]
      resources :tasks, only: [ :index, :show ]
      resources :profiles, only: [ :show ]
      resources :users, only: [:index, :show]

      devise_scope :user do
        post "sign_up", to: "registrations#create"
        post "sign_in", to: "sessions#create"
        post "sign_out", to: "sessions#destroy"
      end


      resources :answers, only: [:show] do
        resources :comments, only: [:index, :show, :create, :update, :destroy]
        resources :likes, only: [:index, :show, :create, :update, :destroy]

        member do
          post 'like', to: 'likes#create'
          delete 'unlike', to: 'likes#destroy'
        end
    
      end



    end
  end

  # Тут пастроим админский неймспейс, маме Максима привет

  # Admin namespace
  namespace :admin do
    resources :themes, except: [ :index, :show ] do
      resources :tasks
    end
    resources :tasks, except: [ :index, :show ] do
      resources :answers
    end
    resources :answers, except: [ :index, :show ] do
      resources :comments
    end

    resources :posts

  end








  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "welcome#index"
end

app/models/theme.rb
class Theme < ApplicationRecord
  has_many :tasks

  mount_uploader :image, TaskImageUploader
end

app/controllers/admin/themes_controller.rb
class Admin::ThemesController < ApplicationController
  load_and_authorize_resource
  before_action :set_theme, only: %i[ show edit update destroy ]

  # GET /themes or /themes.json
  def index
    @themes = Theme.all
  end

  # GET /themes/1 or /themes/1.json
  def show
  end

  # GET /themes/new
  def new
    @theme = Theme.new
  end

  # GET /themes/1/edit
  def edit
  end

  # POST /themes or /themes.json
  def create
    @theme = Theme.new(theme_params)

    respond_to do |format|
      if @theme.save
        format.html { redirect_to @theme, notice: "Theme was successfully created." }
        format.json { render :show, status: :created, location: @theme }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /themes/1 or /themes/1.json
  def update
    respond_to do |format|
      if @theme.update(theme_params)
        format.html { redirect_to @theme, notice: "Theme was successfully updated." }
        format.json { render :show, status: :ok, location: @theme }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /themes/1 or /themes/1.json
  def destroy
    @theme.destroy!

    respond_to do |format|
      format.html { redirect_to themes_path, status: :see_other, notice: "Theme was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_theme
      @theme = Theme.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def theme_params
      params.require(:theme).permit(:theme_title, :theme_descr)
    end
end

app/controllers/api/v1/themes_controller.rb
class Api::V1::ThemesController < ApplicationController
  def index
    @themes = Theme.all
    # render json: @posts
    # render json: @posts.as_json
  end

  def show
    @theme = Theme.find(params[:id])
    @task = @theme.tasks
  end
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  load_and_authorize_resource
  before_action :set_theme, only: %i[ show edit update destroy ]

  # GET /themes or /themes.json
  def index
    @themes = Theme.all
  end

  # GET /themes/1 or /themes/1.json
  def show
  end

  # GET /themes/new
  def new
    @theme = Theme.new
  end

  # GET /themes/1/edit
  def edit
  end

  # POST /themes or /themes.json
  def create
    @theme = Theme.new(theme_params)

    respond_to do |format|
      if @theme.save
        format.html { redirect_to @theme, notice: "Theme was successfully created." }
        format.json { render :show, status: :created, location: @theme }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /themes/1 or /themes/1.json
  def update
    respond_to do |format|
      if @theme.update(theme_params)
        format.html { redirect_to @theme, notice: "Theme was successfully updated." }
        format.json { render :show, status: :ok, location: @theme }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /themes/1 or /themes/1.json
  def destroy
    @theme.destroy!

    respond_to do |format|
      format.html { redirect_to themes_path, status: :see_other, notice: "Theme was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_theme
      @theme = Theme.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def theme_params
      params.require(:theme).permit(:theme_title, :theme_descr)
    end
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/views/themes/_form.html.erb
<%= form_with(model: theme) do |form| %>
  <% if theme.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(theme.errors.count, "error") %> prohibited this theme from being saved:</h2>

      <ul>
        <% theme.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :theme_title, style: "display: block" %>
    <%= form.text_field :theme_title %>
  </div>

  <div>
    <%= form.label :theme_descr, style: "display: block" %>
    <%= form.text_field :theme_descr %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/themes/_theme.html.erb
<div id="<%= dom_id theme %>" class="O_Theme_CardM">

  <div class="A_ThemeCover">
    <%= image_tag theme.theme_cover %>
  </div>

  <div class="M_ThemeText">
      <h1>
        <%= link_to theme.theme_title, theme %>
      </h1>

      <p>
        112 
        <br> 
        таска
      </p>
  </div>


  <%# <%= link_to "Edit this theme", edit_theme_path(@theme) %> 
  <%# <%= link_to "Back to themes", themes_path %>









</div>

app/views/themes/edit.html.erb
<% content_for :title, "Editing theme" %>

<h1>Editing theme</h1>

<%= render "form", theme: @theme %>

<br>

<div>
  <%= link_to "Show this theme", @theme %> |
  <%= link_to "Back to themes", themes_path %>
</div>

app/views/themes/index.html.erb
<p style="color: green"><%= notice %></p>


<%
  set_meta_tags(
    title: "Темы",
    description: "Расшатай привычное представление о скучном дизайне вместе с РеДиз!",
    keywords: "дизайн, редизайн, референсы, вдохновение"
  )
%>

<% content_for :title, "Themes" %>

<% if user_signed_in? && current_user.admin?%>
  <%= link_to "New theme", new_theme_path %>
<% end%>

<div class="M_ThemePageInfo">
  <h1>ТЕМЫ</h1>

  <p>В этом разделе вы найдете список актуальных тем и заданий 
    для редизайна. Выбирайте то, что вам по душе, берите задачу в работу <br> и делитесь своими креативными решениями. </p>
</div>


<div id="themes" class="C_Themes">
    <% @themes.each do |theme| %>
      <%= render theme %>
    <% end %>
</div>

app/views/themes/new.html.erb
<% content_for :title, "New theme" %>

<h1>New theme</h1>

<%= render "form", theme: @theme %>

<br>

<div>
  <%= link_to "Back to themes", themes_path %>
</div>

app/views/themes/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="M_ThemePage">
<%= render @theme %>
</div>

<%
  set_meta_tags(
    title: "Темы",
    description: "Расшатай привычное представление о скучном дизайне вместе с РеДиз!",
    keywords: "дизайн, редизайн, референсы, вдохновение"
  )
%>
<div class="A_NewTask">
  <% if user_signed_in? %>
    <div class="ButtonAction">
      <%= link_to "Добавить таск", new_task_path(theme_id: @theme.id) %>
    </div>
    <%end%>
</div>




<div class="C_Themes">
    <% @theme.tasks.each do |task| %>
      <%= render task %>
    <% end %>
</div>