config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :themes
  resources :posts, only: [:index, :show]
  resources :subscriptions
  resources :profiles

  resources :users do
    resources :comments
    resources :profiles, only: [:new, :create, :show, :edit, :update]
  end

  resources :themes do
    resources :tasks
  end

  resources :posts do
    resources :tasks
  end


  resources :tasks do
    resources :answers

    member do
      post 'like', to: 'likes#create'
      delete 'unlike', to: 'likes#destroy'
    end
  end

  resources :answers do
    resources :comments

    resources :likes, only: [:index, :show, :create, :update, :destroy]

    member do
      post 'like', to: 'likes#create'
      delete 'unlike', to: 'likes#destroy'
    end

  end

  # LOGIN AND AUTHORISE


  # API V1 version, fixing process
  namespace :api, format: "json" do
    namespace :v1 do
      resources :answers, only: [ :index, :show ]
      resources :themes, only: [ :index, :show ]
      resources :tasks, only: [ :index, :show ]
      resources :profiles, only: [ :show ]
      resources :users, only: [:index, :show]

      devise_scope :user do
        post "sign_up", to: "registrations#create"
        post "sign_in", to: "sessions#create"
        post "sign_out", to: "sessions#destroy"
      end


      resources :answers, only: [:show] do
        resources :comments, only: [:index, :show, :create, :update, :destroy]
        resources :likes, only: [:index, :show, :create, :update, :destroy]

        member do
          post 'like', to: 'likes#create'
          delete 'unlike', to: 'likes#destroy'
        end
    
      end



    end
  end

  # Тут пастроим админский неймспейс, маме Максима привет

  # Admin namespace
  namespace :admin do
    resources :themes, except: [ :index, :show ] do
      resources :tasks
    end
    resources :tasks, except: [ :index, :show ] do
      resources :answers
    end
    resources :answers, except: [ :index, :show ] do
      resources :comments
    end

    resources :posts

  end








  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "welcome#index"
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :task
  has_many :comments
  has_many :likes, as: :likeable, dependent: :destroy

  validates :user_name, :answer_img, :description, presence: true


  mount_uploader :answer_img, AnswerImgUploader
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  load_and_authorize_resource
  before_action :set_answer, only: %i[ show edit update destroy ]

  # GET /answers or /answers.json
  def index
    @answers = Answer.all
  end

  # GET /answers/1 or /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @task = Task.find(params[:task_id])
    @answer = Answer.new(task_id: params[:task_id])
  end


  # GET /answers/1/edit
  def edit
  end

  # POST /answers or /answers.json
  def create
    @task = Task.find(params[:task_id])
    @answer = @task.answers.new(answer_params)
    @answer.user_id = current_user

    respond_to do |format|
      if @answer.save
        format.html { redirect_to task_path(@task), notice: "Answer was successfully created." }
        format.json { render :show, status: :created, location: @answer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1 or /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer, notice: "Answer was successfully updated." }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1 or /answers/1.json
  def destroy
    @answer.destroy!

    respond_to do |format|
      format.html { redirect_to answers_path, status: :see_other, notice: "Answer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def answer_params
      params.require(:answer).permit(:user_name, :description, :answer_img, :task_id, :user_id)
    end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < ApplicationController


  def index
    @answers = Answer.all
  end

  def show
      @answer = Answer.includes(:images, :comments).find(params[:id])
      render json: @answer.as_json(
        only: [:id, :user_name, :description, :answer_img, :task_id, :user_id])
  end

  private

   def answer_params
      params.require(:answer).permit(:user_name, :description, :answer_img, :task_id, :user_id)
   end

    def encrypt_payload
      payload = @user.as_json(only: [ :email, :jti ])
      token = JWT.encode(payload, Rails.application.credentials.devise_jwt_secret_key!, "HS256")
    end

    def decrypt_payload
      jwt = request.headers["Authorization"]
      token = JWT.decode(jwt, Rails.application.credentials.devise_jwt_secret_key!, true, { algorithm: "HS256" })
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.erb
<%= link_to (answer)  do %>

<div id="<%= dom_id answer %>" class="C_AnswerCard">

    <div class="M_AnswerTxtContent">
      <div class="A_AnswerTitle">
        REDIZ: <%#= answer.name %>
      </div>
    
      <%= image_tag("icon_pin.png", alt: "Картинка сохранения") %>

    </div>


    <div class="A_AnswerImg">
      <%= image_tag answer.answer_img.url %>
    </div>

    <div class="A_UserNameLink">
      <%= answer.user_name %>
    </div>



  <%# <div class="M_AnswerTXT"> %>
    <%# <p> %>
      <%# <%= answer.user_name %>
    <%# </p> %>

    <%# <p> %>
      <%# <%= answer.description %>
    <%# </p> %>

  <%# </div> %>

  <%# <div class="C_AnswerContent"> %>

    <%# <div class="M_AnswerTopC"> %>
      <%# <div class="A_AnswerProfile"> %>
             <%# <%= link_to "Show this answer", answer %>
      <%# </div> %>

      <%# <div class="A_AnswerTheme"> %>

      <%# </div> %>
    <%# </div> %>





  <%# </div> %>



 


</div>
<% end %>

app/views/answers/_form.html.erb
<%= form_with(model: [@task, answer], local: true) do |form| %>
  <% if answer.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
        <% answer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="O_AnswerForm">


    <div class="M_AnswerImgUpload">
        <%#= form.label :answer_img, style: "display: block" %>
        <%= form.file_field :answer_img %>
    </div>


    <div class="M_AnswerTxTUpload">


      <div class="A_AnswerDesc">
        <%#= form.label :description, style: "display: block" %>
        <%= form.text_field :description, placeholder: "Описание редизки" %>
      </div>

      <div class="ButtonAction">
        <%= form.submit 'Добавить редизку' %>
      </div>

    </div>


  </div>



  <div>
      <%= form.hidden_field :task_id %>
  </div>

  <div>
    <%#= form.label :user_name, style: "display: block" %>
    <%= form.hidden_field :user_name, value: current_user.email %>
  </div>

  <div>
      <%= form.hidden_field :user_id %>
      <%= form.hidden_field :user_name_title, value: current_user.email %>
  </div>


<% end %>

app/views/answers/edit.html.erb
<% content_for :title, "Editing answer" %>

<h1>Editing answer</h1>

<%= render "form", answer: @answer %>

<br>

<div>
  <%= link_to "Show this answer", @answer %> |
  <%= link_to "Back to answers", answers_path %>
</div>

app/views/answers/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Answers" %>



<h1>Answers</h1>

<div id="answers" class="W_Answers">
  <% @answers.each do |answer| %>
    <%= render answer %>
  <% end %>
</div>

<%= link_to "New answer", new_answer_path %>


<%
  set_meta_tags(
    title: "Ответы",
    description: "Расшатай привычное представление о скучном дизайне вместе с РеДиз!",
    keywords: "дизайн, редизайн, референсы, вдохновение"
  )
%>

app/views/answers/new.html.erb
<% content_for :title, "New answer" %>

<div class="M_FormTitle">
  <h1><%= @answer.task.theme.theme_title %></h1>
  <p>новая редизка</p>
</div>


<%= render "form", answer: @answer %>

<br>

<%# <div> %>
  <%# <%= link_to "Back to answers", answers_path %>
<%# </div> %>

app/views/answers/show.html.erb
<%set_meta_tags(
    title: "Ответы",
    description: "Расшатай привычное представление о скучном дизайне вместе с РеДиз!",
    keywords: "дизайн, редизайн, референсы, вдохновение"
  )
%>



<p style="color: green"><%= notice %></p>



<div class="M_RedizkaShow">
  <%= render @answer %>

  <div class="M_UserTaskContent">
    <div class="A_UserTaskName">
      <%= @answer.user_name %>
    </div>
    <div class="A_TaskDescription">
      <%= @answer.description %>
    </div>

    <div class="A_TaskPin">
      <%= image_tag("icon_pin.png", alt: "Картинка сохранения") %>
    </div>

    <div>
      <% if can?(:update, @task) || can?(:destroy, @task) || current_user&.admin? %>
        <%= link_to "Edit this answer", edit_answer_path(@answer) %> |
        <%= button_to "Destroy this answer", @answer, method: :delete %>
      <%end%>
    </div>

  </div>
</div>





<div class="M_CommentSubmit">

  <div class="A_CommentHeader">
    <p>Комментарии</p>
    <hr>
  </div>



    <%= form_for([@answer, @answer.comments.build]) do |f| %>
      <div class="field">
        <%# поменять в контроллере а то смешно %>
        <%= f.label :user_name_title, value: current_user.email %>
      </div>

      <div class="field">
        <%= f.text_area :body_content %>
      </div>

      <div class="actions ButtonAction">
        <%= f.submit %>
      </div>
    <% end %>
</div>

  <div id="comments" class="M_CommentSection">
    <% @answer.comments.each do |comment| %>
      <%= render comment %>
    <% end %>
  </div>