config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :themes
  resources :posts, only: [:index, :show]
  resources :subscriptions
  resources :profiles

  resources :users do
    resources :comments
    resources :profiles, only: [:new, :create, :show, :edit, :update]
  end

  resources :themes do
    resources :tasks
  end

  resources :posts do
    resources :tasks
  end


  resources :tasks do
    resources :answers

    member do
      post 'like', to: 'likes#create'
      delete 'unlike', to: 'likes#destroy'
    end
  end

  resources :answers do
    resources :comments

    resources :likes, only: [:index, :show, :create, :update, :destroy]

    member do
      post 'like', to: 'likes#create'
      delete 'unlike', to: 'likes#destroy'
    end

  end

  # LOGIN AND AUTHORISE


  # API V1 version, fixing process
  namespace :api, format: "json" do
    namespace :v1 do
      resources :answers, only: [ :index, :show ]
      resources :themes, only: [ :index, :show ]
      resources :tasks, only: [ :index, :show ]
      resources :profiles, only: [ :show ]
      resources :users, only: [:index, :show]

      devise_scope :user do
        post "sign_up", to: "registrations#create"
        post "sign_in", to: "sessions#create"
        post "sign_out", to: "sessions#destroy"
      end


      resources :answers, only: [:show] do
        resources :comments, only: [:index, :show, :create, :update, :destroy]
        resources :likes, only: [:index, :show, :create, :update, :destroy]

        member do
          post 'like', to: 'likes#create'
          delete 'unlike', to: 'likes#destroy'
        end
    
      end



    end
  end

  # Тут пастроим админский неймспейс, маме Максима привет

  # Admin namespace
  namespace :admin do
    resources :themes, except: [ :index, :show ] do
      resources :tasks
    end
    resources :tasks, except: [ :index, :show ] do
      resources :answers
    end
    resources :answers, except: [ :index, :show ] do
      resources :comments
    end

    resources :posts

  end








  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "welcome#index"
end

app/models/subscription.rb
class Subscription < ApplicationRecord
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  load_and_authorize_resource
  before_action :set_subscription, only: %i[ show edit update destroy ]

  # GET /subscriptions or /subscriptions.json
  def index
    @subscriptions = Subscription.all
  end

  # GET /subscriptions/1 or /subscriptions/1.json
  def show
  end

  # GET /subscriptions/new
  def new
    @subscription = Subscription.new
  end

  # GET /subscriptions/1/edit
  def edit
  end

  # POST /subscriptions or /subscriptions.json
  def create
    @subscription = Subscription.new(subscription_params)

    respond_to do |format|
      if @subscription.save
        format.html { redirect_to @subscription, notice: "Subscription was successfully created." }
        format.json { render :show, status: :created, location: @subscription }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscriptions/1 or /subscriptions/1.json
  def update
    respond_to do |format|
      if @subscription.update(subscription_params)
        format.html { redirect_to @subscription, notice: "Subscription was successfully updated." }
        format.json { render :show, status: :ok, location: @subscription }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1 or /subscriptions/1.json
  def destroy
    @subscription.destroy!

    respond_to do |format|
      format.html { redirect_to subscriptions_path, status: :see_other, notice: "Subscription was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscription
      @subscription = Subscription.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def subscription_params
      params.fetch(:subscription, {})
    end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_form.html.erb
<%= form_with(model: subscription) do |form| %>
  <% if subscription.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>

      <ul>
        <% subscription.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/subscriptions/_subscription.html.erb
<div id="<%= dom_id subscription %>">
</div>

app/views/subscriptions/edit.html.erb
<% content_for :title, "Editing subscription" %>

<h1>Editing subscription</h1>

<%= render "form", subscription: @subscription %>

<br>

<div>
  <%= link_to "Show this subscription", @subscription %> |
  <%= link_to "Back to subscriptions", subscriptions_path %>
</div>

app/views/subscriptions/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Subscriptions" %>

<h1>Subscriptions</h1>

<div id="subscriptions">
  <% @subscriptions.each do |subscription| %>
    <%= render subscription %>
    <p>
      <%= link_to "Show this subscription", subscription %>
    </p>
  <% end %>
</div>

<%= link_to "New subscription", new_subscription_path %>

app/views/subscriptions/new.html.erb
<% content_for :title, "New subscription" %>

<h1>New subscription</h1>

<%= render "form", subscription: @subscription %>

<br>

<div>
  <%= link_to "Back to subscriptions", subscriptions_path %>
</div>

app/views/subscriptions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @subscription %>

<div>
  <%= link_to "Edit this subscription", edit_subscription_path(@subscription) %> |
  <%= link_to "Back to subscriptions", subscriptions_path %>

  <%= button_to "Destroy this subscription", @subscription, method: :delete %>
</div>