config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :themes
  resources :posts, only: [:index, :show]
  resources :subscriptions
  resources :profiles

  resources :users do
    resources :comments
    resources :profiles, only: [:new, :create, :show, :edit, :update]
  end

  resources :themes do
    resources :tasks
  end

  resources :posts do
    resources :tasks
  end


  resources :tasks do
    resources :answers

    member do
      post 'like', to: 'likes#create'
      delete 'unlike', to: 'likes#destroy'
    end
  end

  resources :answers do
    resources :comments

    resources :likes, only: [:index, :show, :create, :update, :destroy]

    member do
      post 'like', to: 'likes#create'
      delete 'unlike', to: 'likes#destroy'
    end

  end

  # LOGIN AND AUTHORISE


  # API V1 version, fixing process
  namespace :api, format: "json" do
    namespace :v1 do
      resources :answers, only: [ :index, :show ]
      resources :themes, only: [ :index, :show ]
      resources :tasks, only: [ :index, :show ]
      resources :profiles, only: [ :show ]
      resources :users, only: [:index, :show]

      devise_scope :user do
        post "sign_up", to: "registrations#create"
        post "sign_in", to: "sessions#create"
        post "sign_out", to: "sessions#destroy"
      end


      resources :answers, only: [:show] do
        resources :comments, only: [:index, :show, :create, :update, :destroy]
        resources :likes, only: [:index, :show, :create, :update, :destroy]

        member do
          post 'like', to: 'likes#create'
          delete 'unlike', to: 'likes#destroy'
        end
    
      end



    end
  end

  # Тут пастроим админский неймспейс, маме Максима привет

  # Admin namespace
  namespace :admin do
    resources :themes, except: [ :index, :show ] do
      resources :tasks
    end
    resources :tasks, except: [ :index, :show ] do
      resources :answers
    end
    resources :answers, except: [ :index, :show ] do
      resources :comments
    end

    resources :posts

  end








  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "welcome#index"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, Task
    can :read, Theme
    can :read, Answer
    can :read, Profile
    

    return unless user.present?
      can :read, Post
      can :manage, Task, user_id: user.id
      can :manage, Answer, user_id: user.id
      can :manage, Comment, user_id: user.id
      can :manage, Profile, user_id: user.id

    return unless user.admin?
      can :manage, :all












    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :task
  has_many :comments
  has_many :likes, as: :likeable, dependent: :destroy

  validates :user_name, :answer_img, :description, presence: true


  mount_uploader :answer_img, AnswerImgUploader
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :answer
  belongs_to :user

  has_many :replies, class_name: "Comment", foreign_key: "comment_id", dependent: :destroy
  belongs_to :comment, optional: true

  validates :body_content, presence: true

  default_scope { order(created_at: "DESC") }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :likeable, polymorphic: true

  validates :user_id, uniqueness: { scope: [:likeable_id, :likeable_type] }
end

app/models/post.rb
class Post < ApplicationRecord
  has_rich_text :content  # для Markdown с ActionText (если нужен WYSIWYG)
  has_one_attached :cover_image

  validates :title, :published_at, presence: true
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  # validates :name, presence: true

  mount_uploader :image, TaskImageUploader
  # validates :bio, length: { maximum: 300 }
end

app/models/subscription.rb
class Subscription < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
  has_many :answers
  belongs_to :theme
  belongs_to :user

  validates :name, :image, :descroption, presence: true

  mount_uploader :image, TaskImageUploader
end

app/models/theme.rb
class Theme < ApplicationRecord
  has_many :tasks

  mount_uploader :image, TaskImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  include Devise::JWT::RevocationStrategies::JTIMatcher
  has_many :tasks
  has_many :answers
  has_many :comments
  has_many :likes, dependent: :destroy
  has_one :profile, dependent: :destroy #so after deletes user profile delets too

  # after_create :create_user_profile

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :jwt_authenticatable, jwt_revocation_strategy: self


  private
  # In case already has profile so no duplicates are present
  def create_user_profile
    self.create_profile! unless self.profile.present?
  end

end

app/models/welcome.rb
class Welcome < ApplicationRecord
  def index
  end

  def about_us
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<div class="W_Footer">
    <div class="A_Divider"></div>

    <div class="M_Infoblock">

        <div class="A_Smm">
            <h4>follow us</h4>
            <div class="Telegram">
                <%#= image_tag("telegram-outline.png", alt: "telegram follow") %>
                <a href="https://t.me/rediz_media">redis_media</a>
            </div>
            <div class="Git">
                <a href="https://github.com/VarvaraGlushkova/Redis_App">github repository</a>
            </div>
        </div>

        <div class="A_FooterLogo">
            <%= image_tag("logo_footer.png", alt: "telegram follow") %>
        </div>


        <div class="A_Made_By">
            <h4>made by</h4>
            <p>@varvaraseven</p>
            <p>@rootah</p>
            <p>@gabuevaaa</p>
        </div>

        <div class="A_Curated_By">
            <h4>curated by</h4>
            <p>Zakhar Day</p>
            <p>Vadim Bulgakov</p>
        </div>
    </div>

    <div class="M_Additional">

    </div>

</div>

app/views/layouts/_menubar.html.erb
<div class="M_Menubar">



  <%= image_tag("A_Logo_Header.svg", alt: "Картинка логотипа") %>

    <input type="checkbox" id="menu-toggle" class="menu-toggle" />
  <label for="menu-toggle" class="menu-icon">
    <span></span>
    <span></span>
    <span></span>
  </label>

  <div class="menu-drawer">
    <div class="M_LinksHeader">
      <%= link_to 'Главная', root_path %>
      <%= link_to 'Темы', themes_path %>
      <%= link_to 'Блог', posts_path %>
    </div>


    <div class="M_LoginSets">
      <% if current_user %>



        <div class="A_AccentMenu">
          <%= link_to current_user.email, edit_user_registration_path %>
        </div>      

        <%= link_to "Профиль", profile_path(current_user) %>
        <%= link_to "Выйти", destroy_user_session_path, data: { "turbo-method": :delete } %>


      <% else %>

        <%= link_to "Зарегистрироваться", new_user_registration_path %>

        <div class="A_AccentMenu">
          <%= link_to "Войти", new_user_session_path %>
        </div>


      <% end %>
    </div>
  </div>
  
    <div class="M_LinksHeader desktop-only">
      <%= link_to 'Главная', root_path %>
      <%= link_to 'Темы', themes_path %>
      <%= link_to 'Блог', posts_path %>
    </div>


    <div class="M_LoginSets desktop-only">
      <% if current_user %>



        <div class="A_AccentMenu">
          <%= link_to current_user.email, edit_user_registration_path %>
        </div>      

        <%= link_to "Профиль", profile_path(current_user) %>
        <%= link_to "Выйти", destroy_user_session_path, data: { "turbo-method": :delete } %>


      <% else %>

        <%= link_to "Зарегистрироваться", new_user_registration_path %>

        <div class="A_AccentMenu">
          <%= link_to "Войти", new_user_session_path %>
        </div>


      <% end %>
    </div>
  

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Redis App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%= favicon_link_tag 'favicon.png' %>
    <%= tag(:link, rel: 'icon', href: image_path('favicon.png'), type: 'image/png', sizes: '32x32') %>
    <%#= tag(:link, rel: 'apple-touch-icon', href: image_path('apple-touch-icon.png'), sizes: '180x180') %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/menubar' %>
    <p style="color: var(--redis_red, #a2062f)"><%= alert %></p>
    <br>
    <br>
    <br>
    <%# <%= api_v1_tasks_url %>
    <%# <%= api_v1_answers_url %> 
     <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>